export interface ChatSource {
  title: string;
  category: string;
  file: string;
}

export interface GraphNode {
  text: string;
  source: string;
}

export interface ChatStats {
  tps: number;
  context_utilization: number;
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  context_window: number;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  sources: ChatSource[];
  timestamp: Date;
  stats?: ChatStats;
  graphContext?: GraphNode[];
  suggestedPrompts?: string[];
  sub_queries?: string[];
  reflection_loops?: number;
  retrieval_grade?: string;
  answer_grade?: string;
  tools_used?: string[];
  orchestrator_rationale?: string;
  isStreaming?: boolean;
  processingState?: string;
  liveTokenCount?: number;
  error?: boolean;
}

export interface Conversation {
  id: string;
  name: string;
  messages: ChatMessage[];
  createdAt: Date;
  updatedAt: Date;
  /** Latest context utilization (0–1) from last assistant message */
  contextUtilization: number;
  /** Total tokens used in last response */
  totalTokens: number;
  /** Context window size of last response */
  contextWindow: number;
  /** Whether the title was generated by AI (false = default name) */
  titleGenerated: boolean;
  /** Optional custom system prompt for the conversation */
  systemPrompt?: string;
}

export type LlmMode = 'fast' | 'planning';

export interface ChatRequest {
  message: string;
  mode: LlmMode;
  history?: ChatMessage[];
  system_prompt?: string;
}

export interface ChatResponse {
  response: string;
  sources: ChatSource[];
  stats: ChatStats;
  graph_context: GraphNode[];
  query_type: string;
  suggested_prompts?: string[];
  sub_queries?: string[];
  reflection_loops?: number;
  retrieval_grade?: string;
  answer_grade?: string;
  tools_used?: string[];
  orchestrator_rationale?: string;
}

export interface TitleRequest {
  first_message: string;
}

export interface TitleResponse {
  title: string;
}

export interface SuggestionResponse {
  suggestions: string[];
}

